### ISSUE TITLE
新しいタブを開いた時にタブが一部にしか表示されない

### ISSUE THREAD

**Issue by PocoPota** [vcborn/reamix#8]
**Describe the bug**
reamixを起動して新しいタブを開くと、ウィンドウの全画面に表示されるのではなく、左上の一部だけに表示される  
※下記にスクリーンショットあり

**To Reproduce**
1. reamixを起動し、全画面表示(最大化)にする
2. 新しいタブを開く
3. 新しいタブが一部にしか表示されない

**Expected behavior**
新しく生成されるタブがウィンドウの全画面に表示される

**Screenshots**
発生時のスクリーンショット
![image](https://user-images.githubusercontent.com/71576988/177043979-b2cda0df-b10b-47a3-b5dd-f2de1af2b9e8.png)

**Desktop:**
- OS: win11 Pro (insider beta)
- Version: reamix 2.0.0

**Comment by opera7133** [comment]
これで直ったはず https://github.com/vcborn/reamix/commit/5665d609e856eeb5435eab652418531d92f32d7e
